/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProfessoresRouteImport } from './routes/professores'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AreaProfessorRouteImport } from './routes/area-professor'
import { Route as AreaAlunoRouteImport } from './routes/area-aluno'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfessorTurmasRouteImport } from './routes/professor.turmas'
import { Route as ProfessorPerfilRouteImport } from './routes/professor.perfil'
import { Route as ProfessorNotasRouteImport } from './routes/professor.notas'
import { Route as ProfessorMensagensRouteImport } from './routes/professor.mensagens'
import { Route as ProfessorMateriaisRouteImport } from './routes/professor.materiais'
import { Route as ProfessorFrequenciaRouteImport } from './routes/professor.frequencia'
import { Route as ProfessorDashboardRouteImport } from './routes/professor.dashboard'
import { Route as ProfessorAtividadesRouteImport } from './routes/professor.atividades'
import { Route as AlunoPerfilRouteImport } from './routes/aluno.perfil'
import { Route as AlunoNotasRouteImport } from './routes/aluno.notas'
import { Route as AlunoMensagensRouteImport } from './routes/aluno.mensagens'
import { Route as AlunoMateriaisRouteImport } from './routes/aluno.materiais'
import { Route as AlunoFrequenciaRouteImport } from './routes/aluno.frequencia'
import { Route as AlunoDisciplinasRouteImport } from './routes/aluno.disciplinas'
import { Route as AlunoDashboardRouteImport } from './routes/aluno.dashboard'
import { Route as AlunoAtividadesRouteImport } from './routes/aluno.atividades'
import { Route as AdminTurmasRouteImport } from './routes/admin.turmas'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessoresRoute = ProfessoresRouteImport.update({
  id: '/professores',
  path: '/professores',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaProfessorRoute = AreaProfessorRouteImport.update({
  id: '/area-professor',
  path: '/area-professor',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaAlunoRoute = AreaAlunoRouteImport.update({
  id: '/area-aluno',
  path: '/area-aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorTurmasRoute = ProfessorTurmasRouteImport.update({
  id: '/professor/turmas',
  path: '/professor/turmas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorPerfilRoute = ProfessorPerfilRouteImport.update({
  id: '/professor/perfil',
  path: '/professor/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorNotasRoute = ProfessorNotasRouteImport.update({
  id: '/professor/notas',
  path: '/professor/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorMensagensRoute = ProfessorMensagensRouteImport.update({
  id: '/professor/mensagens',
  path: '/professor/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorMateriaisRoute = ProfessorMateriaisRouteImport.update({
  id: '/professor/materiais',
  path: '/professor/materiais',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorFrequenciaRoute = ProfessorFrequenciaRouteImport.update({
  id: '/professor/frequencia',
  path: '/professor/frequencia',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorDashboardRoute = ProfessorDashboardRouteImport.update({
  id: '/professor/dashboard',
  path: '/professor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorAtividadesRoute = ProfessorAtividadesRouteImport.update({
  id: '/professor/atividades',
  path: '/professor/atividades',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoPerfilRoute = AlunoPerfilRouteImport.update({
  id: '/aluno/perfil',
  path: '/aluno/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoNotasRoute = AlunoNotasRouteImport.update({
  id: '/aluno/notas',
  path: '/aluno/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoMensagensRoute = AlunoMensagensRouteImport.update({
  id: '/aluno/mensagens',
  path: '/aluno/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoMateriaisRoute = AlunoMateriaisRouteImport.update({
  id: '/aluno/materiais',
  path: '/aluno/materiais',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoFrequenciaRoute = AlunoFrequenciaRouteImport.update({
  id: '/aluno/frequencia',
  path: '/aluno/frequencia',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoDisciplinasRoute = AlunoDisciplinasRouteImport.update({
  id: '/aluno/disciplinas',
  path: '/aluno/disciplinas',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoDashboardRoute = AlunoDashboardRouteImport.update({
  id: '/aluno/dashboard',
  path: '/aluno/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoAtividadesRoute = AlunoAtividadesRouteImport.update({
  id: '/aluno/atividades',
  path: '/aluno/atividades',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTurmasRoute = AdminTurmasRouteImport.update({
  id: '/admin/turmas',
  path: '/admin/turmas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/area-aluno': typeof AreaAlunoRoute
  '/area-professor': typeof AreaProfessorRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/cursos': typeof CursosRoute
  '/professores': typeof ProfessoresRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/turmas': typeof AdminTurmasRoute
  '/aluno/atividades': typeof AlunoAtividadesRoute
  '/aluno/dashboard': typeof AlunoDashboardRoute
  '/aluno/disciplinas': typeof AlunoDisciplinasRoute
  '/aluno/frequencia': typeof AlunoFrequenciaRoute
  '/aluno/materiais': typeof AlunoMateriaisRoute
  '/aluno/mensagens': typeof AlunoMensagensRoute
  '/aluno/notas': typeof AlunoNotasRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/professor/atividades': typeof ProfessorAtividadesRoute
  '/professor/dashboard': typeof ProfessorDashboardRoute
  '/professor/frequencia': typeof ProfessorFrequenciaRoute
  '/professor/materiais': typeof ProfessorMateriaisRoute
  '/professor/mensagens': typeof ProfessorMensagensRoute
  '/professor/notas': typeof ProfessorNotasRoute
  '/professor/perfil': typeof ProfessorPerfilRoute
  '/professor/turmas': typeof ProfessorTurmasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/area-aluno': typeof AreaAlunoRoute
  '/area-professor': typeof AreaProfessorRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/cursos': typeof CursosRoute
  '/professores': typeof ProfessoresRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/turmas': typeof AdminTurmasRoute
  '/aluno/atividades': typeof AlunoAtividadesRoute
  '/aluno/dashboard': typeof AlunoDashboardRoute
  '/aluno/disciplinas': typeof AlunoDisciplinasRoute
  '/aluno/frequencia': typeof AlunoFrequenciaRoute
  '/aluno/materiais': typeof AlunoMateriaisRoute
  '/aluno/mensagens': typeof AlunoMensagensRoute
  '/aluno/notas': typeof AlunoNotasRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/professor/atividades': typeof ProfessorAtividadesRoute
  '/professor/dashboard': typeof ProfessorDashboardRoute
  '/professor/frequencia': typeof ProfessorFrequenciaRoute
  '/professor/materiais': typeof ProfessorMateriaisRoute
  '/professor/mensagens': typeof ProfessorMensagensRoute
  '/professor/notas': typeof ProfessorNotasRoute
  '/professor/perfil': typeof ProfessorPerfilRoute
  '/professor/turmas': typeof ProfessorTurmasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/area-aluno': typeof AreaAlunoRoute
  '/area-professor': typeof AreaProfessorRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/cursos': typeof CursosRoute
  '/professores': typeof ProfessoresRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/turmas': typeof AdminTurmasRoute
  '/aluno/atividades': typeof AlunoAtividadesRoute
  '/aluno/dashboard': typeof AlunoDashboardRoute
  '/aluno/disciplinas': typeof AlunoDisciplinasRoute
  '/aluno/frequencia': typeof AlunoFrequenciaRoute
  '/aluno/materiais': typeof AlunoMateriaisRoute
  '/aluno/mensagens': typeof AlunoMensagensRoute
  '/aluno/notas': typeof AlunoNotasRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/professor/atividades': typeof ProfessorAtividadesRoute
  '/professor/dashboard': typeof ProfessorDashboardRoute
  '/professor/frequencia': typeof ProfessorFrequenciaRoute
  '/professor/materiais': typeof ProfessorMateriaisRoute
  '/professor/mensagens': typeof ProfessorMensagensRoute
  '/professor/notas': typeof ProfessorNotasRoute
  '/professor/perfil': typeof ProfessorPerfilRoute
  '/professor/turmas': typeof ProfessorTurmasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/area-aluno'
    | '/area-professor'
    | '/cadastro'
    | '/contato'
    | '/cursos'
    | '/professores'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/turmas'
    | '/aluno/atividades'
    | '/aluno/dashboard'
    | '/aluno/disciplinas'
    | '/aluno/frequencia'
    | '/aluno/materiais'
    | '/aluno/mensagens'
    | '/aluno/notas'
    | '/aluno/perfil'
    | '/professor/atividades'
    | '/professor/dashboard'
    | '/professor/frequencia'
    | '/professor/materiais'
    | '/professor/mensagens'
    | '/professor/notas'
    | '/professor/perfil'
    | '/professor/turmas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/area-aluno'
    | '/area-professor'
    | '/cadastro'
    | '/contato'
    | '/cursos'
    | '/professores'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/turmas'
    | '/aluno/atividades'
    | '/aluno/dashboard'
    | '/aluno/disciplinas'
    | '/aluno/frequencia'
    | '/aluno/materiais'
    | '/aluno/mensagens'
    | '/aluno/notas'
    | '/aluno/perfil'
    | '/professor/atividades'
    | '/professor/dashboard'
    | '/professor/frequencia'
    | '/professor/materiais'
    | '/professor/mensagens'
    | '/professor/notas'
    | '/professor/perfil'
    | '/professor/turmas'
  id:
    | '__root__'
    | '/'
    | '/area-aluno'
    | '/area-professor'
    | '/cadastro'
    | '/contato'
    | '/cursos'
    | '/professores'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/turmas'
    | '/aluno/atividades'
    | '/aluno/dashboard'
    | '/aluno/disciplinas'
    | '/aluno/frequencia'
    | '/aluno/materiais'
    | '/aluno/mensagens'
    | '/aluno/notas'
    | '/aluno/perfil'
    | '/professor/atividades'
    | '/professor/dashboard'
    | '/professor/frequencia'
    | '/professor/materiais'
    | '/professor/mensagens'
    | '/professor/notas'
    | '/professor/perfil'
    | '/professor/turmas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreaAlunoRoute: typeof AreaAlunoRoute
  AreaProfessorRoute: typeof AreaProfessorRoute
  CadastroRoute: typeof CadastroRoute
  ContatoRoute: typeof ContatoRoute
  CursosRoute: typeof CursosRoute
  ProfessoresRoute: typeof ProfessoresRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  AdminTurmasRoute: typeof AdminTurmasRoute
  AlunoAtividadesRoute: typeof AlunoAtividadesRoute
  AlunoDashboardRoute: typeof AlunoDashboardRoute
  AlunoDisciplinasRoute: typeof AlunoDisciplinasRoute
  AlunoFrequenciaRoute: typeof AlunoFrequenciaRoute
  AlunoMateriaisRoute: typeof AlunoMateriaisRoute
  AlunoMensagensRoute: typeof AlunoMensagensRoute
  AlunoNotasRoute: typeof AlunoNotasRoute
  AlunoPerfilRoute: typeof AlunoPerfilRoute
  ProfessorAtividadesRoute: typeof ProfessorAtividadesRoute
  ProfessorDashboardRoute: typeof ProfessorDashboardRoute
  ProfessorFrequenciaRoute: typeof ProfessorFrequenciaRoute
  ProfessorMateriaisRoute: typeof ProfessorMateriaisRoute
  ProfessorMensagensRoute: typeof ProfessorMensagensRoute
  ProfessorNotasRoute: typeof ProfessorNotasRoute
  ProfessorPerfilRoute: typeof ProfessorPerfilRoute
  ProfessorTurmasRoute: typeof ProfessorTurmasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professores': {
      id: '/professores'
      path: '/professores'
      fullPath: '/professores'
      preLoaderRoute: typeof ProfessoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-professor': {
      id: '/area-professor'
      path: '/area-professor'
      fullPath: '/area-professor'
      preLoaderRoute: typeof AreaProfessorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-aluno': {
      id: '/area-aluno'
      path: '/area-aluno'
      fullPath: '/area-aluno'
      preLoaderRoute: typeof AreaAlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/turmas': {
      id: '/professor/turmas'
      path: '/professor/turmas'
      fullPath: '/professor/turmas'
      preLoaderRoute: typeof ProfessorTurmasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/perfil': {
      id: '/professor/perfil'
      path: '/professor/perfil'
      fullPath: '/professor/perfil'
      preLoaderRoute: typeof ProfessorPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/notas': {
      id: '/professor/notas'
      path: '/professor/notas'
      fullPath: '/professor/notas'
      preLoaderRoute: typeof ProfessorNotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/mensagens': {
      id: '/professor/mensagens'
      path: '/professor/mensagens'
      fullPath: '/professor/mensagens'
      preLoaderRoute: typeof ProfessorMensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/materiais': {
      id: '/professor/materiais'
      path: '/professor/materiais'
      fullPath: '/professor/materiais'
      preLoaderRoute: typeof ProfessorMateriaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/frequencia': {
      id: '/professor/frequencia'
      path: '/professor/frequencia'
      fullPath: '/professor/frequencia'
      preLoaderRoute: typeof ProfessorFrequenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/dashboard': {
      id: '/professor/dashboard'
      path: '/professor/dashboard'
      fullPath: '/professor/dashboard'
      preLoaderRoute: typeof ProfessorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/atividades': {
      id: '/professor/atividades'
      path: '/professor/atividades'
      fullPath: '/professor/atividades'
      preLoaderRoute: typeof ProfessorAtividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/perfil': {
      id: '/aluno/perfil'
      path: '/aluno/perfil'
      fullPath: '/aluno/perfil'
      preLoaderRoute: typeof AlunoPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/notas': {
      id: '/aluno/notas'
      path: '/aluno/notas'
      fullPath: '/aluno/notas'
      preLoaderRoute: typeof AlunoNotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/mensagens': {
      id: '/aluno/mensagens'
      path: '/aluno/mensagens'
      fullPath: '/aluno/mensagens'
      preLoaderRoute: typeof AlunoMensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/materiais': {
      id: '/aluno/materiais'
      path: '/aluno/materiais'
      fullPath: '/aluno/materiais'
      preLoaderRoute: typeof AlunoMateriaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/frequencia': {
      id: '/aluno/frequencia'
      path: '/aluno/frequencia'
      fullPath: '/aluno/frequencia'
      preLoaderRoute: typeof AlunoFrequenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/disciplinas': {
      id: '/aluno/disciplinas'
      path: '/aluno/disciplinas'
      fullPath: '/aluno/disciplinas'
      preLoaderRoute: typeof AlunoDisciplinasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/dashboard': {
      id: '/aluno/dashboard'
      path: '/aluno/dashboard'
      fullPath: '/aluno/dashboard'
      preLoaderRoute: typeof AlunoDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/atividades': {
      id: '/aluno/atividades'
      path: '/aluno/atividades'
      fullPath: '/aluno/atividades'
      preLoaderRoute: typeof AlunoAtividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/turmas': {
      id: '/admin/turmas'
      path: '/admin/turmas'
      fullPath: '/admin/turmas'
      preLoaderRoute: typeof AdminTurmasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreaAlunoRoute: AreaAlunoRoute,
  AreaProfessorRoute: AreaProfessorRoute,
  CadastroRoute: CadastroRoute,
  ContatoRoute: ContatoRoute,
  CursosRoute: CursosRoute,
  ProfessoresRoute: ProfessoresRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  AdminTurmasRoute: AdminTurmasRoute,
  AlunoAtividadesRoute: AlunoAtividadesRoute,
  AlunoDashboardRoute: AlunoDashboardRoute,
  AlunoDisciplinasRoute: AlunoDisciplinasRoute,
  AlunoFrequenciaRoute: AlunoFrequenciaRoute,
  AlunoMateriaisRoute: AlunoMateriaisRoute,
  AlunoMensagensRoute: AlunoMensagensRoute,
  AlunoNotasRoute: AlunoNotasRoute,
  AlunoPerfilRoute: AlunoPerfilRoute,
  ProfessorAtividadesRoute: ProfessorAtividadesRoute,
  ProfessorDashboardRoute: ProfessorDashboardRoute,
  ProfessorFrequenciaRoute: ProfessorFrequenciaRoute,
  ProfessorMateriaisRoute: ProfessorMateriaisRoute,
  ProfessorMensagensRoute: ProfessorMensagensRoute,
  ProfessorNotasRoute: ProfessorNotasRoute,
  ProfessorPerfilRoute: ProfessorPerfilRoute,
  ProfessorTurmasRoute: ProfessorTurmasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
